version: '2'
services:
  hc-health:
    scale: 1
    start_on_create: true
  hcn-registration:
    retain_ip: true
    scale: 1
    start_on_create: true
  hcn-adapter:
    retain_ip: true
    scale: 1
    start_on_create: true
  hcn-interface:
    scale: 1
    start_on_create: true
  hcn-mpi:
    retain_ip: true
    scale: 1
    start_on_create: true
  hcn-web-slave:
    retain_ip: true
    scale: 1
    start_on_create: true
  admin-old:
    scale: 1
    start_on_create: true
  hcn-pay:
    retain_ip: true
    scale: 1
    start_on_create: true
  fds:
    retain_ip: true
    scale: 1
    start_on_create: true
  pcn-online-consult:
    retain_ip: true
    scale: 1
    start_on_create: true
  hc-interface-demo:
    scale: 1
    start_on_create: true
  pcn-core:
    retain_ip: true
    scale: 1
    start_on_create: true
  pcn-archive-visit:
    scale: 1
    start_on_create: true
  hcn-web-master:
    retain_ip: true
    scale: 1
    start_on_create: true
  hc-wxmp:
    scale: 1
    start_on_create: true
  admin-dist:
    scale: 1
    start_on_create: true
