version: '2'
volumes:
  web-logs:
    external: true
    driver: rancher-nfs
  base-service-logs:
    external: true
    driver: rancher-nfs
  alilife-logs:
    external: true
    driver: rancher-nfs
  wechatclient-logs:
    external: true
    driver: rancher-nfs
  proxy-logs:
    external: true
    driver: rancher-nfs
  file-storage:
    external: true
    driver: rancher-nfs
services:
  proxy:
    image: registry.docker.hc:5000/hc-proxy:3.3.04.1000-SNAPSHOT
    stdin_open: true
    volumes:
    - proxy-logs:/opt/proxy-logs
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    tty: true
    ports:
    - 8090:8090/tcp
    labels:
      traefik.frontend.rule: Host:hol.bsoft.com.cn,10.8.3.66;PathPrefix:/proxy/
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
  file:
    image: registry.docker.hc:5000/hc-file:3.3.04.1000-SNAPSHOT
    stdin_open: true
    volumes:
    - file-storage:/usr/local/tomcat/webapps/ROOT/upload
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    tty: true
    ports:
    - 9000:8080/tcp
    labels:
      traefik.frontend.rule: Host:hol.bsoft.com.cn,10.8.3.66;PathPrefix:/file/
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
  web:
    image: registry.docker.hc:5000/hc-web:3.3.04.1000-SNAPSHOT
    environment:
      common_clinical_url: https://xxxxxx.com.cn/common-clinical/
      hessian_proxy_url: http://proxy:8090/
      hessian_sys_url: http://base-service:8080/
      image_url: https://xxxxxx.com.cn/file-zk/
      regular_replace_pwd: '90'
    stdin_open: true
    volumes:
    - web-logs:/usr/local/tomcat/logs
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    tty: true
    links:
    - base-service:base-service
    - proxy:proxy
    ports:
    - 8096:8080/tcp
    labels:
      traefik.frontend.rule: Host:hol.bsoft.com.cn,10.8.3.66;PathPrefix:/web/
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
  base-service:
    image: registry.docker.hc:5000/hc-base-service:3.3.04.1000-SNAPSHOT
    environment:
      DB_NAME: nethospital_template
      DB_PASS: 1RlQtAX3I5GbI08MTb6rN30lJyqg+sUelxvAyBUte6hguEIRoaOHObBPJijSllszH4lhjp5CMeb/IVUKOpkmZQ==
      DB_PORT: '3306'
      DB_PUBLIC_KEY: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN8MVML+2u6bBOV/lKrnVUYNHRaYf7C9wOYBhtNQkxVa8wXNGO+YfCeJSK+umeMTPjZowFzr+veng02+3TnZYv8CAwEAAQ==
      DB_SVR: 10.8.3.66
      DB_USER: root
      TplCode_kinds_1: ywyyhlw.yzm
      TplCode_kinds_2: ywyyhlw.yzm
      aggregate_desKey: npdtwdDOdV0=
      alipay_app_id: '2018062960428449'
      alipay_charset: utf-8
      alipay_gateway: https://openapi.alipay.com/gateway.do
      alipay_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeaGO0C+M4wBngW8aCzQp1Sdknbq18YYsqVaHme2ZYTitj6C4SaCZhr4yIuk2dXkEWSddgye6uAhT5Ln86bOM80H2YjZNoFYLVDgyqspyIH+7qSw4lJKhPj0NJfgYC4tKo4gDzF2n9APHoAfwEkc4qvYGjXghie/HlwL+bijb863c3CB+bAFTIQut8v5WyShN+vF0laCNNB/pck1hY/mvccAbBJeqsBaH8tGwziO/hX7BXB+xIrBrLiNtAaeFB4wjd5oaQ2f3q7C6qN6TSZSqpSfrhZFUZv9ZkJtaeka0TuT7YGIm2ActAUWZ60iinwZjucgSV/K2ceQ8CRiKX5vGNAgMBAAECggEAT6Q578NB/pRrr7etgjFCSXXEWSZ84UlcuDAp5YrSv1RenUwLE3RQKjLetCdim7OgwwZ2Jaap3Y3JTOGllZpgVOqjzvkDjAYH75s0VfvXqbclqqhtzEcwLi0y/yItrOLkZK1pgaMkxQCNn3L2d/xuQ0fRIFsPzZRsrsUy19PKlQ5hoeSFa5nimr7zpPsr4u/x6RWv9pFxZGqUeVnWYlTL17fWrh1VlNN0JRv++kCeZdagh5Qa4WtcKz3RND3HqjL3WgEpR4aNi4mCiyOcrF8GihiHg4H9deqi4PFCgAFUw5QPqJ5+djhCEp2Zc56QJv6dy9g5VdiINxwZyVpYSt3R0QKBgQDvHZY5R71h6BxnBR1tZUNaav6i6+JPKUw6qaikHORM2PFNyq2HaVdYBDcd0IeUaj/2f4JJPn/+qcw7/Nt7Vr13Vfq9Be/yiQUM/BcLyJfR2ByA609tDCQ/HQJis7sxR6jd33ytlTImXDuKNqGlkVXfAzXsICH5IpZ1bhjzfOhIrwKBgQDuHMf/Mfn4BHsCnRWPQPwyrGukAyO9eSs5Q36J3UtnWl+hB7SbFplr3jhoR96S8Nnt9dc0lfNpgonqKSs4JZZjh72sj+8YJPTlrTAAq0A0BYE8ZLiF4MBHQgkk4fA4HG24UZk1TtvbwEP7Dv/oChX6HwGR08cXRGL2Be247oJAgwKBgDOjVxLNrFddcezJjP5X9QCsxIrYmAnyaDTu+K1gU+lInGvpTipFFIi8eE6m/vCNNXz9Mlyw86FCeAmoZJmxNL91wO1bP+NHteCE/FEeI7M8kYNBzehFy/oZQK+iEtXknNI1dk5iPu9L0cvaWnRP+5RqtBVnJw8PaiC4AwlqOxufAoGADTe/ymTF0YS+J1j892TOGyoDF6ms9DmjspwSjCiipOwZXuEEn49TmO9PBkrnChUgo9r/xUWFq5e5fCwo4AcGICRK3SdoSFjU12MTxRW8jKa5k9arf5MIWWxLAachJJw/Yvn0nUbxYXN80pT0k7brnWTXO3ccGCiNrcaKebeTt20CgYEAgZmRpXP5Ze5tK0+TcVTQh6hYCzLGMJiT/dENvTDKJEJIbKvwc+o1DIFnBiGXYWo+FMOFhJkXElUHA+2BfNMTh3MjNfpJwyF5QEzkP2Jgr1gJGg5PGfaFZvUVos1lAiCdEQvLDu1weGBlX8WDlzo0C9M2FCMotuNxlF2+xtzzv4k=
      alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuWFqfO5B+zmC1IaMBDHmZ5SsWL9Txw/fiT98jdKjRimrFlj6bFIQWLdNszebQ0rrlkaZfL/feqiveuwJHYcQ/6GBZ82+UVh5IQ5AlJdBAJ4Jes/UEqCfT4OFsqEx/MZmKZXrD6N/zRKxCCQakHd+8kb9zYyi6kHj6gdnKaOqg4PnSCcEe8pP7C24P6bkgqLosPIZFB7qa35YRkq7q4z3Iv79IcKGXiwc7xqbc5ngNQjThbnKfqBLbj1MF00CqUx1/4OrI0bs0bNP/Ss4eDUO//aM8siBEibcDw7pv8BKa+zzXNeCLhhTT8FZlnNL7ufU4riTeOQxABcT0GQMqzJ3nQIDAQAB
      alipay_sign_type: RSA2
      apnsProductionFlag: 'true'
      appCode: trtc_test
      appId: trtc_test
      appName: 腾讯云的实时音视频测试
      appSecret: CBIwolSKdK1ovTt50yCNnD1E1iblNZSBfdDzvkexHZHMg9JZCD84DaIJG9iM86z70n5jNdUunacVczdaJXZKM24cDmoBLZTyetq4ToaZhYAYIWg8dWS4okxruOdWvQDS
      appType: subscribe
      app_id: wxc05533898d6fd716
      app_secret: 37618e5603fd1fc158786e8ba5fe5b78
      database_type: '1'
      doctor_overdue_reminder_time: '30'
      hessian_proxy_url: http://proxy:8090/
      hos_name: 创业慧康互联网医院
      huawei_aep_appkey: 16xGt4fcF2UvxovEXWq61936l87a
      huawei_aep_appsecret: 4b3OR2y4H9N1g0Mxs97x95R1zlcD
      huawei_aep_domainname: https://rtcapi.cn-north-1.myhuaweicloud.com:12543
      huawei_areaCode: '0379'
      hzAK: AAAAAAAA
      hzOrgId: sx0001
      hzPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDmIO0QZN1Dvh4yYXjQV/qmY0Tu6+NI7a/+tFZac6avSILOt/pCRVXWSl4Jnwr0jtaiEGFQKQ5cvxnFF5ELOx2eSwfC5/pACEux68fmb3bJPS3VNxqbQyGnGzLQ36/3UpX0gtNnwhOgashRK/5RQRiOiJXdSRJ9KhxQ3bP5x70dpQIDAQAB
      image_url: https://xxxxxx.com.cn/file-zk/
      jpush_doc_appkey: 5b1533caa120f941d68e1666
      jpush_doc_master_secret: 54fbc4df53f5a48510d0e9b0
      jpush_pub_appkey: cfadf50eb56431ee70b8baef
      jpush_pub_master_secret: 20d604c4430658a14a2af4d6
      mini_app_id: wx0c9a13690ee71490
      mini_app_secret: 85f32cfe14e6f29fd4fbae2982408c00
      miniprogramState: trial
      physical_examination_private_key: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAyLjYI3IiLft/vE8gNktXxo3sJxc1UbdeDohqGqWQMtS/XSBwULx5p0haLQOrAMm/gqZRpc52FL7Mh9HqDCxDtwIDAQABAkBaRVdfSZs5ltwxslxITsYhE/7a7cMbBx6T5qHhbghV8y/moQ3mKCoc+ilS4w1RF+szge636wFvFpsFNw513G2BAiEA8qwRwbKbiThZkfhV3WJfDbpUHz8GmJS5LJTyIVIpoNcCIQDTvvaivhvLgnAx+FzZ9+/7QB7ly6zgPnH34i4Cdey4IQIhANzH8evBPMKuMsecITqmagaKVEiNRcoB3SsTY+su3lLHAiAaBMwfoUafEi8hJMicDAhUEkP5rrZWc7XjZMqMiNsGoQIhANVNS6Zo4EiAd6enBmGhdar6EM5rnWLNhGMwYEcif7de
      physical_examination_public_key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMi42CNyIi37f7xPIDZLV8aN7CcXNVG3Xg6IahqlkDLUv10gcFC8eadIWi0DqwDJv4KmUaXOdhS+zIfR6gwsQ7cCAwEAAQ==
      physical_examination_url: http://tijian.atag.bsoft.com.cn/BsoftMECWX/hlwyyLogonAction_main_goIndex_check.do?token=TOKEN&type=2
      prescription_platform_grant_code: zbszxyy2019
      prescription_platform_grant_key: zbszxyy_@2019
      prescription_platform_hos_code: 7cb9c9f90ab705fe
      prescription_platform_url: http://129.211.115.15:8080/pbm-interface/
      privateKey: +CgV4xxaxcZeZrE/pp8TaEbfGbvZiiISho9PSUaXYFYGDB/xmd0krtWP7Ja6zqd3llcR3WteJYPqDO21p0r5M
      project_type: '03'
      publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC9gsi5PE7OZc5CPT1Lx3p7U77v5ln+q0G1noJ+7Dqf96EWFhXO8eovNXe7pzOPATZGMzFtdah2MmZfgoFeMcWsXGXmaxP6afE2hG3xm72YoiEoaPT0lGl2BWBgwf8ZndJK7Vj+yWus6nd5ZXEd1rXiWD6gzttadK+TK/WU7Ns/awIDAQAB
      regular_replace_pwd: '90'
      sf_interface_access_code: TXH_fIuxv
      sf_interface_address: http://bsp-oisp.sf-express.com/bsp-oisp/sfexpressService
      sf_interface_checkword: F1h15YVyJMZof7rv8Azey5fM1GeLqUxm
      sms_platform_appCode: bsoft
      sms_platform_appId: bsoft
      sms_platform_appName: 创业测试
      sms_platform_appSecret: c84f159538354e2f99205f9fbea52f56
      sms_platform_spId: bsoft
      sms_platform_url: http://10.8.3.63:8081/
      spId: bsoft
      sqAK: AAAAAAAA
      sqOrgId: sx0003
      sqPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDmIO0QZN1Dvh4yYXjQV/qmY0Tu6+NI7a/+tFZac6avSILOt/pCRVXWSl4Jnwr0jtaiEGFQKQ5cvxnFF5ELOx2eSwfC5/pACEux68fmb3bJPS3VNxqbQyGnGzLQ36/3UpX0gtNnwhOgashRK/5RQRiOiJXdSRJ9KhxQ3bP5x70dpQIDAQAB
      timeout_operation: '600'
      universalLink: '{"pub":"https://atagmp.bsoft.com.cn/app/hlwyy/pub/","doc":"https://atagmp.bsoft.com.cn/app/hlwyy/pub/","man":"","spe":""}'
      url: https://gateway.atag.bshcn.com.cn/
      verification_minute: '3'
      visitDomainName: http://cs77-3.gdpcloud.com/
      wechat_name: Bsoft互联网健康云平台
      wechat_server_url: https://xxxxxx.com.cn/wechatclient-zk/
      zhumu_password: chinaHANGZHOU
      zhumu_username: bsoft2019
    stdin_open: true
    volumes:
    - base-service-logs:/usr/local/tomcat/logs
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    tty: true
    links:
    - proxy:proxy
    ports:
    - 8095:8080/tcp
    labels:
      traefik.frontend.rule: Host:hol.bsoft.com.cn,10.8.3.66;PathPrefix:/base-service/
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
  alilife:
    image: registry.docker.hc:5000/hc-alilife:3.3.04.1000-SNAPSHOT
    environment:
      alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuWFqfO5B+zmC1IaMBDHmZ5SsWL9Txw/fiT98jdKjRimrFlj6bFIQWLdNszebQ0rrlkaZfL/feqiveuwJHYcQ/6GBZ82+UVh5IQ5AlJdBAJ4Jes/UEqCfT4OFsqEx/MZmKZXrD6N/zRKxCCQakHd+8kb9zYyi6kHj6gdnKaOqg4PnSCcEe8pP7C24P6bkgqLosPIZFB7qa35YRkq7q4z3Iv79IcKGXiwc7xqbc5ngNQjThbnKfqBLbj1MF00CqUx1/4OrI0bs0bNP/Ss4eDUO//aM8siBEibcDw7pv8BKa+zzXNeCLhhTT8FZlnNL7ufU4riTeOQxABcT0GQMqzJ3nQIDAQAB
      app_id: '2018062960428449'
      captchaCountMax: '20'
      hessian_proxy_url: http://proxy:8090/
      hessian_sys_url: http://base-service:8080/
      image_url: https://xxxxxx.com.cn/file-zk/
      private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeaGO0C+M4wBngW8aCzQp1Sdknbq18YYsqVaHme2ZYTitj6C4SaCZhr4yIuk2dXkEWSddgye6uAhT5Ln86bOM80H2YjZNoFYLVDgyqspyIH+7qSw4lJKhPj0NJfgYC4tKo4gDzF2n9APHoAfwEkc4qvYGjXghie/HlwL+bijb863c3CB+bAFTIQut8v5WyShN+vF0laCNNB/pck1hY/mvccAbBJeqsBaH8tGwziO/hX7BXB+xIrBrLiNtAaeFB4wjd5oaQ2f3q7C6qN6TSZSqpSfrhZFUZv9ZkJtaeka0TuT7YGIm2ActAUWZ60iinwZjucgSV/K2ceQ8CRiKX5vGNAgMBAAECggEAT6Q578NB/pRrr7etgjFCSXXEWSZ84UlcuDAp5YrSv1RenUwLE3RQKjLetCdim7OgwwZ2Jaap3Y3JTOGllZpgVOqjzvkDjAYH75s0VfvXqbclqqhtzEcwLi0y/yItrOLkZK1pgaMkxQCNn3L2d/xuQ0fRIFsPzZRsrsUy19PKlQ5hoeSFa5nimr7zpPsr4u/x6RWv9pFxZGqUeVnWYlTL17fWrh1VlNN0JRv++kCeZdagh5Qa4WtcKz3RND3HqjL3WgEpR4aNi4mCiyOcrF8GihiHg4H9deqi4PFCgAFUw5QPqJ5+djhCEp2Zc56QJv6dy9g5VdiINxwZyVpYSt3R0QKBgQDvHZY5R71h6BxnBR1tZUNaav6i6+JPKUw6qaikHORM2PFNyq2HaVdYBDcd0IeUaj/2f4JJPn/+qcw7/Nt7Vr13Vfq9Be/yiQUM/BcLyJfR2ByA609tDCQ/HQJis7sxR6jd33ytlTImXDuKNqGlkVXfAzXsICH5IpZ1bhjzfOhIrwKBgQDuHMf/Mfn4BHsCnRWPQPwyrGukAyO9eSs5Q36J3UtnWl+hB7SbFplr3jhoR96S8Nnt9dc0lfNpgonqKSs4JZZjh72sj+8YJPTlrTAAq0A0BYE8ZLiF4MBHQgkk4fA4HG24UZk1TtvbwEP7Dv/oChX6HwGR08cXRGL2Be247oJAgwKBgDOjVxLNrFddcezJjP5X9QCsxIrYmAnyaDTu+K1gU+lInGvpTipFFIi8eE6m/vCNNXz9Mlyw86FCeAmoZJmxNL91wO1bP+NHteCE/FEeI7M8kYNBzehFy/oZQK+iEtXknNI1dk5iPu9L0cvaWnRP+5RqtBVnJw8PaiC4AwlqOxufAoGADTe/ymTF0YS+J1j892TOGyoDF6ms9DmjspwSjCiipOwZXuEEn49TmO9PBkrnChUgo9r/xUWFq5e5fCwo4AcGICRK3SdoSFjU12MTxRW8jKa5k9arf5MIWWxLAachJJw/Yvn0nUbxYXN80pT0k7brnWTXO3ccGCiNrcaKebeTt20CgYEAgZmRpXP5Ze5tK0+TcVTQh6hYCzLGMJiT/dENvTDKJEJIbKvwc+o1DIFnBiGXYWo+FMOFhJkXElUHA+2BfNMTh3MjNfpJwyF5QEzkP2Jgr1gJGg5PGfaFZvUVos1lAiCdEQvLDu1weGBlX8WDlzo0C9M2FCMotuNxlF2+xtzzv4k=
      public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3mhjtAvjOMAZ4FvGgs0KdUnZJ26tfGGLKlWh5ntmWE4rY+guEmgmYa+MiLpNnV5BFknXYMnurgIU+S5/OmzjPNB9mI2TaBWC1Q4MqrKciB/u6ksOJSSoT49DSX4GAuLSqOIA8xdp/QDx6AH8BJHOKr2Bo14IYnvx5cC/m4o2/Ot3NwgfmwBUyELrfL+VskoTfrxdJWgjTQf6XJNYWP5r3HAGwSXqrAWh/LRsM4jv4V+wVwfsSKway4jbQGnhQeMI3eaGkNn96uwuqjek0mUqqUn64WRVGb/WZCbWnpGtE7k+2BiJtgHLQFFmetIop8GY7nIElfytnHkPAkYil+bxjQIDAQAB
    stdin_open: true
    volumes:
    - alilife-logs:/usr/local/tomcat/logs
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    tty: true
    links:
    - proxy:proxy
    - base-service:base-service
    ports:
    - 8083:8080/tcp
    labels:
      traefik.frontend.rule: Host:hol.bsoft.com.cn,10.8.3.66;PathPrefix:/alilife/
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
  wechatclient:
    image: registry.docker.hc:5000/hc-wechatclient:3.3.04.1000-SNAPSHOT
    environment:
      app_id: wxc05533898d6fd716
      app_secret: 37618e5603fd1fc158786e8ba5fe5b78
      captchaCountMax: '20'
      hessian_proxy_url: http://proxy:8090/
      hessian_sys_url: http://base-service:8080/
      hos_name: 创业慧康互联网医院
      image_url: https://xxxxxx.com.cn/file-zk/
      mini_app_id: wx0c9a13690ee71490
      mini_app_secret: 85f32cfe14e6f29fd4fbae2982408c00
    stdin_open: true
    volumes:
    - wechatclient-logs:/usr/local/tomcat/logs
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    tty: true
    links:
    - base-service:base-service
    - proxy:proxy
    ports:
    - 8882:8080/tcp
    labels:
      traefik.frontend.rule: Host:hol.bsoft.com.cn,10.8.3.66;PathPrefix:/wechatclient/
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
