version: '2'
volumes:
  zkdata:
    driver: local
    per_container: true
  zkconfig:
    driver: local
    per_container: true
services:
  ckb-zookeeper:
    image: rawmind/alpine-zk:3.4.10-0
    environment:
      CONFD_INTERVAL: '60'
      JVMFLAGS: -Xmx512m -Xms512m
      ZK_DATA_DIR: /opt/zk/data
      ZK_INIT_LIMIT: '10'
      ZK_MAX_CLIENT_CXNS: '500'
      ZK_SYNC_LIMIT: '5'
      ZK_TICK_TIME: '2000'
    stdin_open: true
    tty: true
    volumes_from:
    - zk-volume
    - zk-conf
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: zk-conf,zk-volume
      io.rancher.container.hostname_override: container_name
  zk-conf:
    image: rawmind/rancher-zk:3.4.9
    network_mode: none
    volumes:
    - zkconfig:/opt/tools
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  zk-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10002'
      SERVICE_UID: '10002'
      SERVICE_VOLUME: /opt/zk/data
    network_mode: none
    volumes:
    - zkdata:/opt/zk/data
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  bs-ckb:
    image: registry.cn-hangzhou.aliyuncs.com/jk/bs-ckb:latest
    environment:
      LOCALHOST_PORT: localhost
      LOCALHOST_IP: '8080'
      RPC_LUCENE_DISK: /usr/local/ckb/luceneindex
      DIS_COMPATH: /usr/local/ckb/common_desease
      ZOOKEEPER_SERVER: ckb-zookeeper:2181
      RPC_SERVER: 0.0.0.0:49005
      RPC_HCN_DISEASELIBRARY_SERVER: 183.58.24.160:37303
    stdin_open: true
    volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
    tty: true
    links:
    - ckb-zookeeper:ckb-zookeeper
    ports:
    - 49005:49005/tcp
    labels:
      io.rancher.container.pull_image: always