version: '2'
services:
  redis-slave:
    image: registry.cn-hangzhou.aliyuncs.com/jk/redis-slave:latest
    stdin_open: true
    volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
    tty: true
    links:
    - redis-master:redis-master
    labels:
      io.rancher.container.pull_image: always
  redis-master:
    image: registry.cn-hangzhou.aliyuncs.com/jk/redis-master:latest
    stdin_open: true
    volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
    tty: true
    ports:
    - 6379:6379/tcp
    labels:
      io.rancher.container.pull_image: always
  redis-sentinel:
    image: registry.cn-hangzhou.aliyuncs.com/jk/redis-sentinel:latest
    stdin_open: true
    volumes:
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
    tty: true
    links:
    - redis-master:redis-master
    - redis-slave:redis-slave
