version: '2'
services:
  gateway-lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 8800:8800/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
