version: '2'
volumes:
  jenkins:
    external: true
    driver: rancher-nfs
services:
  jenkins:    
    image: jenkins/jenkins
    stdin_open: true
    volumes:
    - jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/ip:/etc/ip
    - /usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    - /usr/bin/docker:/usr/bin/docker
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    tty: true    
    ports:
    - 8082:8080/tcp
    user: root
    labels:      
      io.rancher.container.pull_image: always
  registry:
    image: registry
    stdin_open: true
    volumes:
    - /hc/data/repository:/var/lib/registry
    tty: true
    ports:
    - 5000:5000/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: registry_lb=true   
